### ISSUE TITLE
Display IRC connection status on SIGUSR1

### ISSUE THREAD

**Issue by gagath** [haum/hms_irc#1]
The bot can occasionally crash during netsplits. We do not know why but in order to debug the state of the bot after the netsplit occurs we need to display all information we have about the connection to the IRC server.

This emergency debug displaying can be triggered when the program receives a SIGUSR1 system signal.

**Comment by matael** [comment]
PR #2 was proposed without looking at this issue and break the SIGUSR1=>IRC status request. Though, it should provide a way to overcome the netsplit problem by starting hms_irc.ircbot.serv.connect() upon catching SIGUSR1.

All is in the 10 lines of matael/hms_irc@74f4a9e

**Comment by gagath** [comment]
Using SIGUSR1 for reconnection rather than just displaying info is a good idea. Closing this issue.
