### ISSUE TITLE
Periodicaly send SIGUSR1 to reconnect to the server

### ISSUE THREAD

**Issue by gagath** [haum/hms_irc#3]
On SIGUSR1 the bot will try to reconnect to the server. We shall now send periodic SIGUSR1 in order to make the bot reconnect in case of netsplit.
However the current behavior is that systemd will restart the whole microservice in a periodic way. What may be the advantages of sending SIGUSR1 instead of restarting the service? (ping @Matael)

**Comment by matael** [comment]
Now 74f4a9e has been merged, sending SIGUSR1 will start a reconnection attempt. There's two effects:
- if the bot is still connected: pass silently (no deco/reco, improvement compared to the current method)
- If the bot is deconnected: reconnection (same effect as current)

**Comment by gagath** [comment]
During a netsplit it is not obvious to me that the bot will be disconnected from the IRC server, because it is a disconnection between 2 servers rather than a disconnection between the microservice and the IRC server. I am not very confortable with the IRC protocol so I may be wrong.

Nonetheless this will allow us to get rid of the current join/part messages by reconnecting only if disconnected for some reason.
